---
title: "CFHCyear1"
author: "Katherine Antosca"
date: "11/27/2018"
output: word_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
#load necessary libraries
library(dada2)
library(ShortRead)
library(ggplot2)
library(breakaway)
library(DivNet)
library(corncob)
library(magrittr)
library(dplyr)
library(vegan)
library(phyloseq)
library(ade4)
library(car)
library(phangorn)
library(multcomp)
library(RColorBrewer)
library(GUniFrac)
library(pheatmap)
library(prettyPCoA)
library(ggsignif)
library(DECIPHER)
library(pheatmap)
library(scatterplot3d)
library(Rtsne)
library(gganimate)
library(gifski)
library(png)
library(lme4)
```




```{r alpha, echo = FALSE}
#read in sample data
sampdf <- read.csv("ClinData.csv")
rownames(sampdf) <- sampdf$mblid

#Remove CF samples after the 1 year time point
year1seqtab <- seqtab.nochim[which(rownames(seqtab.nochim) %in% rownames(sampdf)),]


#Check row order
sampdf <- sampdf[match(rownames(year1seqtab), sampdf$mblid),]
rownames(sampdf) == rownames(year1seqtab)

#convert to phyloseq object

phylo <- phyloseq(otu_table(year1seqtab, taxa_are_rows=FALSE), 
               sample_data(sampdf), 
               tax_table(taxa)) 



alphadiv <- estimate_richness(phylo)
#extract shannon diversity and add it to sampdf
Shannon <- alphadiv$Shannon
Simpson <- alphadiv$Simpson
sampdf <- cbind(sampdf, Shannon, Simpson)
#Set order for plotting by age and Status
sampdf$TimePeriod <- factor(sampdf$TimePeriod, levels = c("6W","4M","6M","9M","12M"))
sampdf$Status <- factor(sampdf$Status, levels = c("HC","CF"))
#Color palettes
Greens <- c("darkolivegreen1","chartreuse","springgreen3","chartreuse4","#003300")
  #c("#00FF00","#74C476","#33CC33","#006600","#003300") blues -> #3366FF,"#000088""#00CCFF",
Blues <- c("#00FFFF","deepskyblue", "royalblue1","slateblue3","#0000FF")
Pinks <- c("#FF99FF","#FF66CC","#FF3399","violetred","deeppink4")
Purples <- c("#CC99FF","mediumpurple2","mediumorchid","mediumorchid4","#660099")
Reds <- c("#FF3333","firebrick2","#CC0033","#990000","indianred4")
Oranges <- c("#FFFF00","#FFCC00","#FF9900","#FF6600","darkorange4")
GreenBlues <- as.vector(rbind(Greens, Blues))
brewer.pal(5,"Greens")

plot(1:10,1:10,col =Blues ,pch = 19,cex = 2)
plot(1:30,1:30,col = Rainbow,pch = 19,cex = 2)
Rainbow <- as.vector(cbind(Pinks[1:4], Reds[2:4], Oranges[1:4], Greens[1:4], Blues[1:4], Purples[1:4]))
Rainbow2 <- as.vector(cbind(Blues[1:4], Greens[1:4], Oranges[1:4], Pinks[1:4], Purples[1:4]))
Rainbow2[4] <- Blues[5]

wilcox.test(sampdf$Shannon[sampdf$TimePeriod == "6W"]~sampdf$Status[sampdf$TimePeriod == "6W"])
wilcox.test(sampdf$Shannon[sampdf$TimePeriod == "4M"]~sampdf$Status[sampdf$TimePeriod == "4M"])
wilcox.test(sampdf$Shannon[sampdf$TimePeriod == "6M"]~sampdf$Status[sampdf$TimePeriod == "6M"])
wilcox.test(sampdf$Shannon[sampdf$TimePeriod == "9M"]~sampdf$Status[sampdf$TimePeriod == "9M"])
wilcox.test(sampdf$Shannon[sampdf$TimePeriod == "12M"]~sampdf$Status[sampdf$TimePeriod == "12M"])

p.adjust(8.093e-05, method = "fdr", n=5)

```  

```{r HCalphaplot, echo = FALSE}
HCalphaplot <- ggplot(data = sampdf[sampdf$Status=="HC",], aes(x = TimePeriod, y = Shannon, 
                                                               group = TimePeriod)) + 
  geom_boxplot(fill = Greens, color = "black") + 
  geom_signif(comparisons = list(c("6W", "12M")), map_signif_level=TRUE) +
  theme_bw(base_size = 25) +
  xlab("Age in Months") +
  scale_x_discrete(labels = c("1M","4M","6M","9M","12M"))
HCalphaplot
pdf(file = "ShannonHC2.pdf",height = 8, width = 12)
  HCalphaplot
dev.off()
```
```{r CFalphaplot, echo = FALSE}
CFalphaplot <- ggplot(data = sampdf[sampdf$Status=="CF",], aes(x = TimePeriod, y = Shannon, group = TimePeriod)) + geom_boxplot(fill = Blues, color = "black") +
  geom_signif(comparisons = list(c("6W", "12M")), map_signif_level=TRUE) +
  theme_bw(base_size = 25) +
  xlab("Age in Months") +
  scale_x_discrete(labels = c("1M","4M","6M","9M","12M"))
CFalphaplot
pdf(file = "ShannonCF2.pdf",height = 8, width = 12)
  CFalphaplot
dev.off()
```

```{r CFalphaPulmEx, echo = FALSE}
CFalphaB4PulmEx <- ggplot(data = sampdf[sampdf$Status=="CF",], aes(x = B4PulmEx, y = Shannon)) + geom_boxplot(fill = c(Blues[3],Blues[5]), color = "black") +
  geom_signif(comparisons = list(c( "no","yes")), map_signif_level=TRUE) +
  theme_bw(base_size = 25) +
  xlab("Before first exacerbation") +
  scale_x_discrete(labels = c("no","yes"))
CFalphaB4PulmEx

wilcox.test(sampdf$Shannon[sampdf$StatusAge=="6W HC"|sampdf$StatusAge=="12M HC"]~sampdf$TimePeriod[sampdf$StatusAge=="6W HC"|sampdf$StatusAge=="12M HC"])
wilcox.test(sampdf$Shannon[sampdf$Status=="CF"]~sampdf$B4PulmEx[sampdf$Status=="CF"])
p.adjust(2.2e-16, method ="fdr", n= 5)

pdf(file = "ShannonCF.pdf",height = 8, width = 12)
  CFalphaplot
dev.off()
```

```{r alphaplot, echo = FALSE}
alphaplot <- ggplot(data = sampdf, aes(x = TimePeriod, y = Shannon, color = Status)) + 
  geom_boxplot(fill = GreenBlues) +
  scale_color_manual(values = c("darkgreen", "mediumblue"), 
                     labels = c("General Population", "Cystic Fibrosis"))+
  theme_bw(base_size = 25) +
  xlab("Age in Months") +
  scale_x_discrete(labels = c("1M","4M","6M","9M","12M"))
alphaplot
pdf(file = "ShannonAll2.pdf",height = 8, width = 14)
  alphaplot
dev.off()
sampdf$StatusAge <- factor(sampdf$StatusAge, 
                           levels = c("6W HC", "4M HC", "6M HC","9M HC","12M HC",
                                     "6W CF","4M CF", "6M CF", "9M CF", "12M CF"))
pdf(file = "ShannonAll3.pdf",height = 8, width = 14)
  ggplot(data = sampdf, aes(x = StatusAge, y = Shannon)) + 
  geom_boxplot(fill = c(Greens,Blues) ) +
  theme_bw(base_size = 25) +
  xlab("Age and Status")
dev.off()
  
sampdf$StatusAge <- factor(sampdf$StatusAge, 
                           levels = c("6W CF","4M CF", "6M CF", "9M CF", "12M CF",
                                      "6W HC", "4M HC", "6M HC","9M HC","12M HC"))

PancAll <- sampdf$PancIns
PancAll[sampdf$Status == "HC"] <- "No"
PulmExAll <- sampdf$PulmEx1yr
PulmExAll[sampdf$Status == "HC"] <- "No"
summary(glm(sampdf$Shannon~sampdf$TimePeriod+sampdf$Status+sampdf$dFeedingModeED + PancAll + PulmExAll))

```

```{r subHC, echo = FALSE}





```





```{r beta, echo = FALSE}
#extracting ASV table
ASV <- as.data.frame(phylo@otu_table@.Data)
#check that ASV matched samples dataframe
rownames(ASV) == rownames(sampdf)
CFASV <- ASV[sampdf$Status=="CF",]
CFsamp <- sampdf[sampdf$Status == "CF",]
#extract tree
tree <- fitGTR$tree
tree <- midpoint(tree)

#calculate GUnifracDistances
unifracs <- GUniFrac(ASV, tree, alpha = c(0, 0.5, 1))$unifracs
#extract distance 0.5
d5 <- unifracs[,,"d_0.5"]
d1<- unifracs[,,"d_1"]
#PERMANOVA
adonis(as.dist(d1) ~ sampdf$TimePeriod + sampdf$Status + sampdf$dFeedingModeED)
adonis(as.dist(d5[sampdf$TimePeriod == "6W",sampdf$TimePeriod == "6W"]) ~ sampdf$Status[sampdf$TimePeriod == "6W"])
adonis(as.dist(d5[sampdf$TimePeriod == "4M",sampdf$TimePeriod == "4M"]) ~ sampdf$Status[sampdf$TimePeriod == "4M"])
adonis(as.dist(d5[sampdf$TimePeriod == "6M",sampdf$TimePeriod == "6M"]) ~ sampdf$Status[sampdf$TimePeriod == "6M"])
adonis(as.dist(d5[sampdf$TimePeriod == "9M",sampdf$TimePeriod == "9M"]) ~ sampdf$Status[sampdf$TimePeriod == "9M"])
adonis(as.dist(d5[sampdf$TimePeriod == "12M",sampdf$TimePeriod == "12M"]) ~ sampdf$Status[sampdf$TimePeriod == "12M"])
adonis(as.dist(d5[sampdf$Status == "HC",sampdf$Status == "HC"]) ~ sampdf$dFeedingModeED[sampdf$Status == "HC"])
#running again for CF samples
CFunifracs <- GUniFrac(CFASV, tree, alpha = c(0, 0.5, 1))$unifracs
#extract distance 0.5
CFd5 <- CFunifracs[,,"d_0.5"]
CFd1 <- CFunifracs[,,"d_1"]
#PERMANOVA
adonis(as.dist(CFd5) ~ CFsamp$B4PulmEx)
adonis(as.dist(CFd5) ~ CFsamp$PulmEx1yr)
adonis(as.dist(CFd5) ~ CFsamp$PancIns)
adonis(as.dist(CFd5) ~ CFsamp$dFeedingModeED)
adonis(as.dist(CFd5) ~ CFsamp$TimePeriod)
adonis(as.dist(CFd5) ~ CFsamp$DeliveryMode)
adonis(as.dist(CFd5) ~ CFsamp$Sex)
adonis(as.dist(CFd5) ~ CFsamp$TimePeriod + CFsamp$PulmEx1yr)
adonis(as.dist(CFd5) ~ CFsamp$TimePeriod + CFsamp$B4PulmEx)
adonis(as.dist(CFd5[CFsamp$TimePeriod == "6W" ,CFsamp$TimePeriod == "6W"]) ~ CFsamp$PulmEx1yr[CFsamp$TimePeriod == "6W"])
adonis(as.dist(CFd5[CFsamp$TimePeriod == "4M" ,CFsamp$TimePeriod == "4M"]) ~ CFsamp$PulmEx1yr[CFsamp$TimePeriod == "4M"])
adonis(as.dist(CFd5[CFsamp$TimePeriod == "6M" ,CFsamp$TimePeriod == "6M"]) ~ CFsamp$PulmEx1yr[CFsamp$TimePeriod == "6M"])
adonis(as.dist(CFd5[CFsamp$TimePeriod == "9M" ,CFsamp$TimePeriod == "9M"]) ~ CFsamp$PulmEx1yr[CFsamp$TimePeriod == "9M"])
adonis(as.dist(CFd5[CFsamp$TimePeriod == "12M" ,CFsamp$TimePeriod == "12M"]) ~ CFsamp$PulmEx1yr[CFsamp$TimePeriod == "12M"])

adonis(as.dist(d5[sampdf$PancIns != "Yes"|sampdf$Status=="HC",sampdf$PancIns != "Yes"|sampdf$Status=="HC"]) ~sampdf$TimePeriod[sampdf$PancIns != "Yes"|sampdf$Status=="HC"] + sampdf$Status[sampdf$PancIns != "Yes"|sampdf$Status=="HC"])



CFpcs <- pcoa(CFd5, correction = "cailliez")
CFpc1_2 <- CFpcs$vectors[,1:2]
colnames(CFpc1_2) <- c("PC1","PC2")
CFsamp <- cbind(CFsamp,CFpc1_2)
CFpcs$values$Broken_stick[1:2]
pcs$values$Broken_stick[1:2]

colnames(d5) == sampdf$mblid  
Pcs6W <- pcoa(d5[sampdf$TimePeriod == "6W",sampdf$TimePeriod == "6W"], correction = "cailliez")
Pcs4M <- pcoa(d5[sampdf$TimePeriod == "4M",sampdf$TimePeriod == "4M"], correction = "cailliez")
Pcs6M <- pcoa(d5[sampdf$TimePeriod == "6M",sampdf$TimePeriod == "6M"], correction = "cailliez")
Pcs9M <- pcoa(d5[sampdf$TimePeriod == "9M",sampdf$TimePeriod == "9M"], correction = "cailliez")
Pcs12M <- pcoa(d5[sampdf$TimePeriod == "12M",sampdf$TimePeriod == "12M"], correction = "cailliez")

#ordination for plotting
pcs <- pcoa(d5, correction = "cailliez")

rownames(sampdf) == rownames(pcs$vectors)
#modify  sample data for plotting
sampdf <- cbind(sampdf, pcs$vectors[,1:3])

sampdf$StatusAge <- paste(sampdf$TimePeriod,sampdf$Status)
sampdf$StatusAge <- factor(sampdf$StatusAge, 
                           levels = c("6W HC","6W CF", "4M HC","4M CF", "6M HC", "6M CF",
                                      "9M HC","9M CF", "12M HC","12M CF"))

pdf(file = "betaAll2.pdf", height = 8, width = 12)
ggplot(sampdf[sampdf$TimePeriod != "6W",], aes(Axis.1,Axis.2, color = StatusAge)) + 
  geom_point(size = 4) +
   labs(x = "PC 1", y = "PC 2")+
  theme_bw(base_size = 25) +
  scale_color_manual(values = c(GreenBlues[3:10]), name = "Age Status")
dev.off()
#reversing database to plot HC samples first and adding age based PCoA columns
revsamp <- sampdf[nrow(sampdf):1,]

pdf(file = "betaAlltime.pdf", height = 8.5, width = 12)
ggplot(revsamp, aes(Axis.1,Axis.2, color = StatusAge)) + 
  geom_point(size = 3) +
  labs(x = "PC 1", y = "PC 2")+
  theme_bw(base_size = 25) +
  scale_color_manual(values = c(Blues,Greens), name = "Age Status")+
  facet_wrap(revsamp$TimePeriod,labeller = as_labeller(c("6W" = "6 Weeks","4M" = "4 Months", "6M" = "6 Months", "9M" = "9 Months", "12M" = "12 Months")) )+
  stat_ellipse()+ 
  theme(legend.position = c(1, 0), legend.justification = c(1.25, 0))
dev.off()

pdf(file = "betaPancSufAll.pdf", height = 8, width = 12)
ggplot(sampdf[sampdf$PancIns != "Yes"|sampdf$Status=="HC"&sampdf$TimePeriod != "6W",], aes(Axis.1,Axis.2, color = StatusAge)) + 
  geom_point(size = 4) +
   labs(x = "PC 1", y = "PC 2")+
  theme_bw(base_size = 25) +
  scale_color_manual(values = c(GreenBlues[2:10],GreenBlues[3:4]), name = "Age Status")
dev.off()

#+
 # stat_ellipse(aes(group= sampdf$Status[sampdf$PancIns != "Yes"|sampdf$Status=="HC"&sampdf$TimePeriod != "6W"]))
```

```{r timepointBeta, echo = FALSE}

#Calculating PCs from distance matrix
Pcs6W <- pcoa(d5[sampdf$TimePeriod == "6W",sampdf$TimePeriod == "6W"], correction = "cailliez")
Pcs4M <- pcoa(d5[sampdf$TimePeriod == "4M",sampdf$TimePeriod == "4M"], correction = "cailliez")
Pcs6M <- pcoa(d5[sampdf$TimePeriod == "6M",sampdf$TimePeriod == "6M"], correction = "cailliez")
Pcs9M <- pcoa(d5[sampdf$TimePeriod == "9M",sampdf$TimePeriod == "9M"], correction = "cailliez")
Pcs12M <- pcoa(d5[sampdf$TimePeriod == "12M",sampdf$TimePeriod == "12M"], correction = "cailliez")

dat6W <-sampdf[sampdf$TimePeriod == "6W",]

pdf(file = "beta6W.pdf", height = 8, width = 12)
ggplot(dat6W, aes(Pcs6W$vectors[,1],Pcs6W$vectors[,2], color = Status)) + 
  geom_point(size = 5) +
  geom_point(data = dat6W[dat6W$StatusAge == "6W CF",], aes(Pcs6W$vectors[dat6W$StatusAge == "6W CF",1],Pcs6W$vectors[dat6W$StatusAge == "6W CF",2]),size = 5) +
   labs(x = "PC 1", y = "PC 2")+
  theme_bw(base_size = 20) +
  scale_color_manual(values = GreenBlues[5:6],name = "Health Staus", labels = c( "Control","Cystic Fibrosis"))+
  stat_ellipse()
dev.off()

library("rgl")
plot3d(Pcs6W$vectors[,1],Pcs6W$vectors[,2],Pcs6W$vectors[,3])

```


```{r feedingBeta, echo = FALSE}

pdf(file = "betaFeeding2.pdf", height = 8, width = 12)
ggplot(sampdf[sampdf$TimePeriod != "6W",], aes(Axis.1,Axis.2, color = StatusAge, shape = as.factor(dFeedingModeED))) + 
  scale_shape_manual(values = c(15,17,1),name = "Feeding Mode", labels = c("Breast", "Formula", "Mixed"))+
  geom_point(size = 5) +
   labs(x = "PC 1", y = "PC 2")+
  theme_bw(base_size = 20) +
  scale_color_manual(values = GreenBlues[3:10], name = "Age Status")  
dev.off()

```

```{r CFbeta feeding, echo = FALSE}

pdf(file = "betaCFfeeding.pdf", height = 8, width = 12)
ggplot(sampdf[sampdf$Status =="CF",], aes(Axis.1,Axis.2, color = TimePeriod, shape = as.factor(dFeedingModeED))) + 
  scale_shape_manual(values = c(15,17,1),name = "Feeding Mode", labels = c("Breast", "Formula", "Mixed"))+ 
  geom_point(size = 4) +
   labs(x = "PC 1", y = "PC 2")+
  theme_bw(base_size = 25) +
  scale_color_manual(values = Blues, name = "Age")
dev.off()

pdf(file = "betaCFfeeding2.pdf", height = 8, width = 12)
ggplot(CFsamp, aes(PC1,PC2, color = TimePeriod, shape = as.factor(dFeedingModeED))) + 
  scale_shape_manual(values = c(15,17,1),name = "Feeding Mode", labels = c("Breast", "Formula", "Mixed"))+ 
  geom_point(size = 5) +
   labs(x = "PC 1", y = "PC 2")+
  theme_bw(base_size = 25) +
  scale_color_manual(values = Blues, name = "Age")
dev.off()

```

```{r HC beta, echo = FALSE}
HC1 <- sampdf[sampdf$unq_id == "ah_80014963",]
HC1$TimePeriod
HC1 <- HC1[c(4,2,3,5,1),]
HC2 <- sampdf[sampdf$unq_id == "ah_80014967",]
HC2 <- HC2[c(4,2,3,5,1),]
HC3 <- sampdf[sampdf$unq_id == "ah_80013785",]
HC3 <- HC3[c(4,2,3,5,1),]
HC4 <- sampdf[sampdf$unq_id == "ah_80014035",]
HC4 <- HC4[c(4,2,3,5,1),]
#I should have just written a function to do this but I was in a hurry and not thinking at the time..
pdf(file = "betaHCAge.pdf", height = 8, width = 12)
ggplot(sampdf[sampdf$Status =="HC",], aes(Axis.1,Axis.2, color = TimePeriod)) + 
  geom_point(size = 4) +
   labs(x = "PC 1", y = "PC 2")+
  theme_bw(base_size = 25) +
  scale_color_manual(values = Greens, name = "Age")
dev.off()
pdf(file = "betaHCAgeProg1.pdf", height = 8, width = 12)
ggplot(sampdf[sampdf$Status =="HC",], aes(Axis.1,Axis.2, color = TimePeriod)) +
  geom_point(size = 4) +
   labs(x = "PC 1", y = "PC 2")+
  theme_bw(base_size = 25) +
  scale_color_manual(values = c(Greens), name = "Age")+
  geom_point(data = HC1[1,], shape = 17, color =   Pinks[1],size = 8)+
  geom_point(data = HC2[1,], shape = 17, color = Oranges[1],size = 8)+
  geom_point(data = HC3[1,], shape = 17, color = Purples[1],size = 8)+
  geom_point(data = HC4[1,], shape = 17, color =    Reds[1],size = 8)
dev.off()
pdf(file = "betaHCAgeProg2.pdf", height = 8, width = 12)
ggplot(sampdf[sampdf$Status =="HC",], aes(Axis.1,Axis.2, color = TimePeriod)) +
  geom_point(size = 4) +
   labs(x = "PC 1", y = "PC 2")+
  theme_bw(base_size = 25) +
  scale_color_manual(values = c(Greens), name = "Age")+
  geom_path(data = HC1[1:2,], color = Pinks[1:2],size = 2, lineend = "round")+
  geom_path(data = HC2[1:2,], color = Oranges[1:2],size = 2, lineend = "round")+
  geom_path(data = HC3[1:2,], color = Purples[1:2],size = 2, lineend = "round")+
  geom_path(data = HC4[1:2,], color = Reds[1:2],size = 2, lineend = "round")+
  geom_point(data = HC1[1,], color = Pinks[1],size = 5)+
  geom_point(data = HC2[1,], color = Oranges[1],size = 5)+
  geom_point(data = HC3[1,], color = Purples[1],size = 5)+
  geom_point(data = HC4[1,], color = Reds[1],size = 5)+
  geom_point(data = HC1[2,], shape = 17, color =   Pinks[2],size = 8)+
  geom_point(data = HC2[2,], shape = 17, color = Oranges[2],size = 8)+
  geom_point(data = HC3[2,], shape = 17, color = Purples[2],size = 8)+
  geom_point(data = HC4[2,], shape = 17, color =    Reds[2],size = 8)
dev.off()

pdf(file = "betaHCAgeProg3.pdf", height = 8, width = 12)
ggplot(sampdf[sampdf$Status =="HC",], aes(Axis.1,Axis.2, color = TimePeriod)) +
  geom_point(size = 4) +
   labs(x = "PC 1", y = "PC 2")+
  theme_bw(base_size = 25) +
  scale_color_manual(values = c(Greens), name = "Age")+
  geom_path(data = HC1[1:3,], color = Pinks[1:3],size = 2, lineend = "round")+
  geom_path(data = HC2[1:3,], color = Oranges[1:3],size = 2, lineend = "round")+
  geom_path(data = HC3[1:3,], color = Purples[1:3],size = 2, lineend = "round")+
  geom_path(data = HC4[1:3,], color = Reds[1:3],size = 2, lineend = "round")+
  geom_point(data = HC1[1:2,], color = Pinks[1:2],size = 5)+
  geom_point(data = HC2[1:2,], color = Oranges[1:2],size = 5)+
  geom_point(data = HC3[1:2,], color = Purples[1:2],size = 5)+
  geom_point(data = HC4[1:2,], color = Reds[1:2],size = 5)+
  geom_point(data = HC1[3,], shape = 17, color =   Pinks[3],size = 8)+
  geom_point(data = HC2[3,], shape = 17, color = Oranges[3],size = 8)+
  geom_point(data = HC3[3,], shape = 17, color = Purples[3],size = 8)+
  geom_point(data = HC4[3,], shape = 17, color =    Reds[3],size = 8)
dev.off()
pdf(file = "betaHCAgeProg4.pdf", height = 8, width = 12)
ggplot(sampdf[sampdf$Status =="HC",], aes(Axis.1,Axis.2, color = TimePeriod)) +
  geom_point(size = 4) +
   labs(x = "PC 1", y = "PC 2")+
  theme_bw(base_size = 25) +
  scale_color_manual(values = c(Greens), name = "Age")+
  geom_path(data = HC1[1:4,], color = Pinks[1:4],size = 2, lineend = "round")+
  geom_path(data = HC2[1:4,], color = Oranges[1:4],size = 2, lineend = "round")+
  geom_path(data = HC3[1:4,], color = Purples[1:4],size = 2, lineend = "round")+
  geom_path(data = HC4[1:4,], color = Reds[1:4],size = 2, lineend = "round")+
  geom_point(data = HC1[1:3,], color = Pinks[1:3],size = 5)+
  geom_point(data = HC2[1:3,], color = Oranges[1:3],size = 5)+
  geom_point(data = HC3[1:3,], color = Purples[1:3],size = 5)+
  geom_point(data = HC4[1:3,], color = Reds[1:3],size = 5)+
  geom_point(data = HC1[4,], shape = 17, color =   Pinks[4],size = 8)+
  geom_point(data = HC2[4,], shape = 17, color = Oranges[4],size = 8)+
  geom_point(data = HC3[4,], shape = 17, color = Purples[4],size = 8)+
  geom_point(data = HC4[4,], shape = 17, color =    Reds[4],size = 8)
dev.off()

pdf(file = "betaHCAgeProg5.pdf", height = 8, width = 12)
ggplot(sampdf[sampdf$Status =="HC",], aes(Axis.1,Axis.2, color = TimePeriod)) +
  geom_point(size = 4) +
   labs(x = "PC 1", y = "PC 2")+
  theme_bw(base_size = 25) +
  scale_color_manual(values = c(Greens), name = "Age")+
  geom_path(data = HC1[1:5,], color = Pinks[1:5],size = 2, lineend = "round")+
  geom_path(data = HC2[1:5,], color = Oranges[1:5],size = 2, lineend = "round")+
  geom_path(data = HC3[1:5,], color = Purples[1:5],size = 2, lineend = "round")+
  geom_path(data = HC4[1:5,], color = Reds[1:5],size = 2, lineend = "round")+
  geom_point(data = HC1[1:4,], color = Pinks[1:4],size = 5)+
  geom_point(data = HC2[1:4,], color = Oranges[1:4],size = 5)+
  geom_point(data = HC3[1:4,], color = Purples[1:4],size = 5)+
  geom_point(data = HC4[1:4,], color = Reds[1:4],size = 5)+
  geom_point(data = HC1[5,], shape = 17, color =   Pinks[5],size = 8)+
  geom_point(data = HC2[5,], shape = 17, color = Oranges[5],size = 8)+
  geom_point(data = HC3[5,], shape = 17, color = Purples[5],size = 8)+
  geom_point(data = HC4[5,], shape = 17, color =    Reds[5],size = 8)
dev.off()
```

```{r CF beta, echo = FALSE}

pdf(file = "betaCFAge.pdf", height = 8, width = 12)
ggplot(sampdf[sampdf$Status =="CF",], aes(Axis.1,Axis.2, color = TimePeriod)) + 
  geom_point(size = 4) +
   labs(x = "PC 1", y = "PC 2")+
  theme_bw(base_size = 25) +
  scale_color_manual(values = Blues, name = "Age")
dev.off()
CF1 <- CFsamp[CFsamp$unq_id == "116",]
CF2 <- CFsamp[CFsamp$unq_id == "124",]
CF3 <- CFsamp[CFsamp$unq_id == "126",] 
CF4 <- CFsamp[CFsamp$unq_id == "130",]
  
pdf(file = "betaCFAge2.pdf", height = 8, width = 12)
ggplot(CFsamp, aes(PC1,PC2, color = TimePeriod)) + 
  geom_point(size = 4) +
   labs(x = "PC 1", y = "PC 2")+
  theme_bw(base_size = 25) +
  scale_color_manual(values = Blues, name = "Age")
dev.off()

pdf(file = "betaCFAge2prog1.pdf", height = 8, width = 12)
ggplot(CFsamp, aes(PC1,PC2, color = TimePeriod)) + 
  geom_point(size = 4) +
   labs(x = "PC 1", y = "PC 2")+
  theme_bw(base_size = 25) +
  scale_color_manual(values = Blues, name = "Age")+
  geom_point(data = CF1[1,],shape = 17, color =   Pinks[1],size = 8)+
  geom_point(data = CF2[1,],shape = 17, color = Oranges[1],size = 8)+
  geom_point(data = CF3[1,],shape = 17, color = Purples[1],size = 8)+
  geom_point(data = CF4[1,],shape = 17, color =    Reds[1],size = 8)

dev.off()
pdf(file = "betaCFAge2prog2.pdf", height = 8, width = 12)
ggplot(CFsamp, aes(PC1,PC2, color = TimePeriod)) + 
  geom_point(size = 4) +
   labs(x = "PC 1", y = "PC 2")+
  theme_bw(base_size = 25) +
  scale_color_manual(values = Blues, name = "Age")+
  geom_path(data = CF1[1:2,], color = Pinks[1:2],size = 2, lineend = "round")+
  geom_path(data = CF2[1:2,], color = Oranges[1:2],size = 2, lineend = "round")+
  geom_path(data = CF3[1:2,], color = Purples[1:2],size = 2, lineend = "round")+
  geom_path(data = CF4[1:2,], color = Reds[1:2],size = 2, lineend = "round")+
  geom_point(data = CF1[1,], color = Pinks[1],size = 5)+
  geom_point(data = CF2[1,], color = Oranges[1],size = 5)+
  geom_point(data = CF3[1,], color = Purples[1],size = 5)+
  geom_point(data = CF4[1,], color = Reds[1],size = 5)+
  geom_point(data = CF1[2,],shape = 17, color =   Pinks[2],size = 8)+
  geom_point(data = CF2[2,],shape = 17, color = Oranges[2],size = 8)+
  geom_point(data = CF3[2,],shape = 17, color = Purples[2],size = 8)+
  geom_point(data = CF4[2,],shape = 17, color =    Reds[2],size = 8)
dev.off()

pdf(file = "betaCFAge2prog3.pdf", height = 8, width = 12)
ggplot(CFsamp, aes(PC1,PC2, color = TimePeriod)) + 
  geom_point(size = 4) +
   labs(x = "PC 1", y = "PC 2")+
  theme_bw(base_size = 25) +
  scale_color_manual(values = Blues, name = "Age")+
  geom_path(data = CF1[1:3,], color = Pinks[1:3],size = 2, lineend = "round")+
  geom_path(data = CF2[1:3,], color = Oranges[1:3],size = 2, lineend = "round")+
  geom_path(data = CF3[1:3,], color = Purples[1:3],size = 2, lineend = "round")+
  geom_path(data = CF4[1:3,], color = Reds[1:3],size = 2, lineend = "round")+
  geom_point(data = CF1[1:2,], color = Pinks[1:2],size = 5)+
  geom_point(data = CF2[1:2,], color = Oranges[1:2],size = 5)+
  geom_point(data = CF3[1:2,], color = Purples[1:2],size = 5)+
  geom_point(data = CF4[1:2,], color = Reds[1:2],size = 5)+
  geom_point(data = CF1[3,],shape = 17, color =   Pinks[3],size = 8)+
  geom_point(data = CF2[3,],shape = 17, color = Oranges[3],size = 8)+
  geom_point(data = CF3[3,],shape = 17, color = Purples[3],size = 8)+
  geom_point(data = CF4[3,],shape = 17, color =    Reds[3],size = 8)
dev.off()

pdf(file = "betaCFAge2prog4.pdf", height = 8, width = 12)
ggplot(CFsamp, aes(PC1,PC2, color = TimePeriod)) + 
  geom_point(size = 4) +
   labs(x = "PC 1", y = "PC 2")+
  theme_bw(base_size = 25) +
  scale_color_manual(values = Blues, name = "Age")+
  geom_path(data = CF1[1:4,], color = Pinks[1:4],size = 2, lineend = "round")+
  geom_path(data = CF2[1:4,], color = Oranges[1:4],size = 2, lineend = "round")+
  geom_path(data = CF3[1:4,], color = Purples[1:4],size = 2, lineend = "round")+
  geom_path(data = CF4[1:4,], color = Reds[1:4],size = 2, lineend = "round")+
  geom_point(data = CF1[1:3,], color = Pinks[1:3],size = 5)+
  geom_point(data = CF2[1:3,], color = Oranges[1:3],size = 5)+
  geom_point(data = CF3[1:3,], color = Purples[1:3],size = 5)+
  geom_point(data = CF4[1:3,], color = Reds[1:3],size = 5)+
  geom_point(data = CF1[4,],shape = 17, color =   Pinks[4],size = 8)+
  geom_point(data = CF2[4,],shape = 17, color = Oranges[4],size = 8)+
  geom_point(data = CF3[4,],shape = 17, color = Purples[4],size = 8)+
  geom_point(data = CF4[4,],shape = 17, color =    Reds[4],size = 8)
dev.off()

pdf(file = "betaCFAge2prog5.pdf", height = 8, width = 12)
ggplot(CFsamp, aes(PC1,PC2, color = TimePeriod)) + 
  geom_point(size = 4) +
   labs(x = "PC 1", y = "PC 2")+
  theme_bw(base_size = 25) +
  scale_color_manual(values = Blues, name = "Age")+
  geom_path(data = CF1[1:5,], color = Pinks[1:5],size = 2, lineend = "round")+
  geom_path(data = CF2[1:5,], color = Oranges[1:5],size = 2, lineend = "round")+
  geom_path(data = CF3[1:5,], color = Purples[1:5],size = 2, lineend = "round")+
  geom_path(data = CF4[1:5,], color = Reds[1:5],size = 2, lineend = "round")+
  geom_point(data = CF1[1:4,], color = Pinks[1:4],size = 5)+
  geom_point(data = CF2[1:4,], color = Oranges[1:4],size = 5)+
  geom_point(data = CF3[1:4,], color = Purples[1:4],size = 5)+
  geom_point(data = CF4[1:4,], color = Reds[1:4],size = 5)+
  geom_point(data = CF1[5,],shape = 17, color =   Pinks[5],size = 8)+
  geom_point(data = CF2[5,],shape = 17, color = Oranges[5],size = 8)+
  geom_point(data = CF3[5,],shape = 17, color = Purples[5],size = 8)+
  geom_point(data = CF4[5,],shape = 17, color =    Reds[5],size = 8)
dev.off()

```

```{r CF beta Panc, echo = FALSE}


pdf(file = "betaCFPanc.pdf", height = 8, width = 12)
ggplot(sampdf[sampdf$Status =="CF",], aes(Axis.1,Axis.2, shape = PancIns, color = PancIns)) + 
  geom_point(size = 4) +
   labs(x = "PC 1", y = "PC 2") +
  theme_bw(base_size = 25) + 
  scale_shape_manual(values =c(17,19), name = "Pancreas", labels = c("Sufficient", "Insufficient")) +
 scale_color_manual(values =Blues[2:4], name = "Pancreas", labels = c("Sufficient", "Insufficient"))

dev.off()

pdf(file = "betaCFPanc2.pdf", height = 8, width = 12)
ggplot(CFsamp, aes(PC1,PC2, shape = PancIns, color = PancIns)) + 
  geom_point(size = 5) +
   labs(x = "PC 1", y = "PC 2") +
  theme_bw(base_size = 25) + 
  scale_shape_manual(values =c(17,19), name = "Pancreas", labels = c("Sufficient", "Insufficient")) +
 scale_color_manual(values =Blues[2:5], name = "Pancreas", labels = c("Sufficient", "Insufficient"))

dev.off()
```

```{r CF beta PulmEx, echo = FALSE}


pdf(file = "betaCFPulmEx.pdf", height = 8, width = 12)
ggplot(sampdf[sampdf$Status =="CF",], aes(Axis.1,Axis.2, shape = PulmEx1yr, color = PulmEx1yr)) + 
  geom_point(size = 4) +
   labs(x = "PC 1", y = "PC 2 (5%)") +
  theme_bw(base_size = 25) + 
  scale_shape_manual(values =c(17,19), name = "Exacerbation", labels = c("No", "Yes")) +
 scale_color_manual(values =Blues[2:5], name = "Exacerbation", labels = c("No", "Yes"))
dev.off()

pdf(file = "betaCFPulmEx2.pdf", height = 8, width = 12)
ggplot(CFsamp, aes(PC1,PC2, shape = PulmEx1yr, color = PulmEx1yr)) + 
  geom_point(size = 5) +
   labs(x = "PC 1 (7%)", y = "PC 2 (5%)") +
  theme_bw(base_size = 25) + 
  scale_shape_manual(values =c(17,19), name = "Exacerbation", labels = c("No", "Yes")) +
 scale_color_manual(values =Blues[2:5], name = "Exacerbation", labels = c("No", "Yes"))
dev.off()

#add group means and lines
mns <- CFsamp %>% 
        group_by(PulmEx1yr, TimePeriod) %>% 
        summarise(x = mean(PC1), y = mean(PC2))

pdf(file = "betaCFPulmEx3Ellipse.pdf", height = 8, width = 12)
ggplot(CFsamp, aes(PC1,PC2, shape = PulmEx1yr, color = PulmEx1yr)) + 
  geom_point(size = 5) +
   labs(x = "PC 1 (7%)", y = "PC 2 (5%)") +
  theme_bw(base_size = 25) + 
  scale_shape_manual(values =c(17,19), name = "Exacerbation", labels = c("No", "Yes")) +
 scale_color_manual(values =Blues[2:5], name = "Exacerbation", labels = c("No", "Yes"))+
  facet_wrap(CFsamp$TimePeriod, labeller = as_labeller(c("6W" = "6 Weeks","4M" = "4 Months", "6M" = "6 Months", "9M" = "9 Months", "12M" = "12 Months")))+
  stat_ellipse()+
  theme(legend.position = c(1, 0.25), legend.justification = c(1.1, 0))
dev.off()

pdf(file = "betaCFPulmEx3.pdf", height = 8, width = 12)
ggplot(CFsamp, aes(PC1,PC2, shape = PulmEx1yr, color = PulmEx1yr)) + 
  geom_point(size = 5) +
   labs(x = "PC 1 (7%)", y = "PC 2 (5%)") +
  theme_bw(base_size = 25) + 
  scale_shape_manual(values =c(17,19), name = "Exacerbation", labels = c("No", "Yes")) +
 scale_color_manual(values =Blues[2:5], name = "Exacerbation", labels = c("No", "Yes"))+
  facet_wrap(CFsamp$TimePeriod, labeller = as_labeller(c("6W" = "6 Weeks","4M" = "4 Months", "6M" = "6 Months", "9M" = "9 Months", "12M" = "12 Months")))+
  theme(legend.position = c(1, 0.25), legend.justification = c(1.1, 0))
dev.off()
```

```{r CF beta b4PulmEx, echo = FALSE}


pdf(file = "betaCFB4PulmEx.pdf", height = 8, width = 12)
ggplot(sampdf[sampdf$Status =="CF",], aes(Axis.1,Axis.2, shape = B4PulmEx, color = B4PulmEx)) + 
  geom_point(size = 4) +
   labs(x = "PC 1", y = "PC 2") +
  theme_bw(base_size = 25) + 
  scale_shape_manual(values =c(17,19), name = "Before Pulm Ex", labels = c("No", "Yes")) +
 scale_color_manual(values =Blues[2:5], name = "Before Pulm Ex", labels = c("No", "Yes"))
dev.off()

pdf(file = "betaCFB4PulmEx2.pdf", height = 8, width = 12)
ggplot(CFsamp, aes(PC1,PC2, shape = B4PulmEx, color = B4PulmEx)) + 
  geom_point(size = 5) +
   labs(x = "PC 1", y = "PC 2") +
  theme_bw(base_size = 25) + 
  scale_shape_manual(values =c(17,19), name = "Before Pulm Ex", labels = c("No", "Yes")) +
 scale_color_manual(values =Blues[2:5], name = "Before Pulm Ex", labels = c("No", "Yes"))
dev.off()

```

```{r CF beta delmode, echo = FALSE}


pdf(file = "betaCFDelMode.pdf", height = 8, width = 12)
ggplot(sampdf[sampdf$Status =="CF",], aes(Axis.1,Axis.2, shape = DeliveryMode, color = DeliveryMode)) + 
  geom_point(size = 4) +
   labs(x = "PC 1", y = "PC 2") +
  theme_bw(base_size = 25) + 
  scale_shape_manual(values =c(17,19), name = "Delivery Mode", labels = c("C-Section", "Vaginal")) +
 scale_color_manual(values =Blues[2:5], name = "Delivery Mode", labels = c("C-Section", "Vaginal"))
dev.off()

pdf(file = "betaCFDelMode2.pdf", height = 8, width = 12)
ggplot(CFsamp, aes(PC1,PC2, shape = DeliveryMode, color = DeliveryMode)) + 
  geom_point(size = 5) +
   labs(x = "PC 1", y = "PC 2") +
  theme_bw(base_size = 25) + 
  scale_shape_manual(values =c(17,19), name = "Delivery Mode", labels = c("C-Section", "Vaginal")) +
 scale_color_manual(values =Blues[2:5], name = "Delivery Mode", labels = c("C-Section", "Vaginal"))
dev.off()

```

```{r CF beta Sex, echo = FALSE}


pdf(file = "betaCFSex.pdf", height = 8, width = 12)
ggplot(sampdf[sampdf$Status =="CF",], aes(Axis.1,Axis.2, shape = Sex, color = Sex)) + 
  geom_point(size = 4) +
   labs(x = "PC 1", y = "PC 2") +
  theme_bw(base_size = 25) + 
  scale_shape_manual(values =c(17,19), name = "Sex", labels = c("Female", "Male")) +
 scale_color_manual(values =Blues[2:5], name = "Sex", labels = c("Female", "Male"))
dev.off()

pdf(file = "betaCFSex2.pdf", height = 8, width = 12)
ggplot(CFsamp, aes(PC1,PC2, shape = Sex, color = Sex)) + 
  geom_point(size = 5) +
   labs(x = "PC 1", y = "PC 2") +
  theme_bw(base_size = 25) + 
  scale_shape_manual(values =c(17,19), name = "Sex", labels = c("Female", "Male")) +
 scale_color_manual(values =Blues[2:5], name = "Sex", labels = c("Female", "Male"))
dev.off()


```

```{r tSNE, echo = FALSE}

#testing out t-Distributed Stochastic Neighbor Embedding(tSNE) plots
#setting seed for consistent output
set.seed(333)

tSNEtest<- Rtsne(d5,dims=2,perplexity= 75, is_distance = TRUE)

ggplot(sampdf[sampdf$TimePeriod != "6W",], aes(tSNEtest$Y[sampdf$TimePeriod != "6W",1],tSNEtest$Y[sampdf$TimePeriod != "6W",2], color = StatusAge)) + 
  geom_point(size = 3) +
   labs(x = "PC 1", y = "PC 2")+
  theme_bw(base_size = 25) +
  scale_color_manual(values = GreenBlues[3:10], name = "Age Status")


```


```{r heatmap, echo = FALSE}

#Prepping ASV table for heatmap


heatmap <- plot_heatmap(phylo)

pdf("heatmap.pdf")
heatmap
dev.off()


```



```{r taxa, echo = FALSE}

multcomtaxa <- mt(phylo, "Status")
multcomtaxa$adjp
multcomtaxa$Genus[1:25]
write.csv(multcomtaxa, file = "CFHCtaxaComp.csv")
BactCounts <- colSums(phylo@otu_table@.Data)[multcomtaxa$index[which(multcomtaxa$Genus == "Bacteroides")]]
Bacteroides <- cbind(multcomtaxa[which(multcomtaxa$Genus == "Bacteroides"),], BactCounts)
write.csv(Bacteroides, file = "Bacteroides.csv")




phylo6W <-phylo %>% subset_samples(TimePeriod %in% "6W") 
phylo4M <-phylo %>% subset_samples(TimePeriod %in% "4M") 
phylo6M <-phylo %>% subset_samples(TimePeriod %in% "6M") 
phylo9M <-phylo %>% subset_samples(TimePeriod %in% "9M") 
phylo12M <-phylo %>% subset_samples(TimePeriod %in% "12M") 
phyloCF <-phylo %>% subset_samples(Status %in% "CF") 
multcomtaxa6W <- mt(phylo6W, "Status")
multcomtaxa4M <- mt(phylo4M, "Status")
multcomtaxa6M <- mt(phylo6M, "Status")
multcomtaxa9M <- mt(phylo9M, "Status")
multcomtaxa12M <- mt(phylo12M, "Status")
multcomtaxaPulmEx <- mt(phyloCF, "PulmEx1yr")
multcomtaxaPanc <- mt(phyloCF, "PancIns")

write.csv(multcomtaxa6W, file = "CFHCtaxa6W.csv")
write.csv(multcomtaxa4M, file = "CFHCtaxa4M.csv")
write.csv(multcomtaxa9M, file = "CFHCtaxa9M.csv")
write.csv(multcomtaxa12M, file = "CFHCtaxa12M.csv")
write.csv(multcomtaxa6M, file = "CFHCtaxa6M.csv")
write.csv(multcomtaxaPulmEx, file = "CFHCtaxaPulmEx.csv")
write.csv(multcomtaxaPanc, file = "CFHCtaxaPanc.csv")


multcompRA <- mt(phylo20RA, "Status")
write.csv(multcompRA,file = "CFHCtop20.csv")


phyloGenus <- tax_glom(phylo,taxrank = "Genus", NArm = FALSE)

multcompGenus <- mt(phyloGenus, "Status")

write.csv(multcompGenus, file = "CFHCGenus.csv")

phyloCFgenus <- tax_glom(phyloCF, taxrank = "Genus", NArm = FALSE)

mtCFPulmExGenus <- mt(phyloCFgenus, "PulmEx1yr")
write.csv(mtCFPulmExGenus, file = "CFPulmExGenus.csv")

RAphylo <- transform_sample_counts(phyloGenus, function(x) x / sum(x))
rowSums(RAphylo@otu_table@.Data)
mergeStat <- merge_samples(RAphylo, sampdf$Status)
mergeStat<- transform_sample_counts(mergeStat, function(x) x / sum(x))
mergeStat20 <- prune_taxa(Top20,mergeStat)
rowSums(mergeStat20@otu_table@.Data)



rowSums(phylo20@otu_table@.Data)
#top 20 for bar plot
Top20 <- names(sort(taxa_sums(phyloGenus), TRUE)[1:20])
phylo20 <- prune_taxa(Top20, phyloGenus)

phylo20StatAge <- merge_samples(phylo20, sampdf$StatusAge)
phylo20RA <- transform_sample_counts(phylo20, function(x) x / sum(x))
phylo20StatAgeRA <- transform_sample_counts(phylo20StatAge, function(x) x / sum(x))
rowSums(phylo20StatAgeRA@otu_table@.Data)
rowSums(phylo20RA@otu_table@.Data)

phylo20StatAgeRA@tax_table[,6]
phylo20StatAgeRA@otu_table[,5]

pdf("RABarplotTest.pdf", height = 20, width = 20)
plot_bar(phylo20StatAgeRA) 
dev.off()

BPtestOTU <- phylo20StatAgeRA@otu_table
colnames(BPtestOTU) <- phylo20StatAgeRA@tax_table[,6]
colnames(BPtestOTU)[4]<-paste("o_",phylo20StatAgeRA@tax_table[4,5], "_g_NA",sep="")
colnames(BPtestOTU)
#reshaping data got ggplot
BPtest2 <- psmelt(BPtestOTU)
colnames(BPtest2) <- c("Genus","Sample","Abundance")
BPtest2$Sample <- factor(BPtest2$Sample, levels = c("6W CF","4M CF","6M CF", "9M CF", "12M CF",
                                                    "6W HC","4M HC","6M HC", "9M HC", "12M HC"))
BPtest2 <- BPtest2[order(BPtest2$Abundance),]
BPtest2$Age <-factor(gsub( " .*$", "",BPtest2$Sample), levels = c("6W","4M","6M","9M","12M"))
BPtest2$Status <- factor(substr(BPtest2$Sample, nchar(as.vector(BPtest2$Sample))-1,nchar(as.vector(BPtest2$Sample))))

colors = c( "#D896FF", "#E30074", "#FF4E50", "#FC913A", "#FFAAA5", "#FFD3B6", "#EAE374", "#F9D62E",  
             "#8AE429", "#E2F4C7", "#9AFE2E", "#FE00F6", "#77AAFF", "#99CCFF", "#FF9900",
             "#A8E6CF", "#00F9FF", "#005EFF", "#009FFF", "#0900FF", "#00308F", "#B8D000", "#4D7F17", "#6BB120",
             "#BBEEFF", "#800080", "#BE29EC", "#EFBBFF", "#FF8B94", "#0392CF", "#FDF498", "#FFD4E5", "#D4FFEA",
             "#EECBFF", "#DBDCFF", "#FE0000", "#E08822", "#5E8EB7", "#BD5757", "#EE4035", 
             "#73BA9F", "#FDFE02", "#9BA2FF", "#D4CAC5")

pdf("RABarplot2.pdf", height = 10, width = 20)
 ggplot(BPtest2, aes(x = Status, y = Abundance, fill = Genus, group = Abundance)) + geom_bar(stat = 'identity') +
   theme_bw(base_size =28)+ 
   theme(legend.position = "bottom",legend.text = element_text(face = "italic")) + 
   scale_fill_manual(values = Rainbow2) +xlab("Age and Health Status") +ylab("Relative Abundance %")+
  scale_y_continuous(labels = c("0","25","50","75","100"))+
   facet_wrap(BPtest2$Age, labeller = as_labeller(c("6W" = "6 Weeks","4M" = "4 Months", "6M" = "6 Months", "9M" = "9 Months", "12M" = "12 Months")),ncol = 5 )
dev.off()

pdf("RABarplot3.pdf", height = 10, width = 20)
 ggplot(BPtest2, aes(x = Age, y = Abundance, fill = Genus, group = Abundance)) + geom_bar(stat = 'identity') + 
   theme_bw(base_size =28)+ 
   theme(legend.position = "bottom",legend.text = element_text(face = "italic")) +
   scale_fill_manual(values = Rainbow2) +xlab("Age and Health Status") +ylab("Relative Abundance %")+
  scale_y_continuous(labels = c("0","25","50","75","100"))+
   facet_wrap(BPtest2$Status, labeller = as_labeller(c("CF" = "CF","HC" = "Control")),ncol = 2 )
dev.off()

```

```{r CFbarplot, echo = FALSE}

CFBarplotOTU <- as.data.frame(phylo20RA@otu_table)[phylo20RA@sam_data$Status == "CF",]
colnames(CFBarplotOTU) <- phylo20RA@tax_table[,6]
colnames(CFBarplotOTU)[4]<-paste("o_",phylo20RA@tax_table[4,5], "_g_NA",sep="")
colnames(CFBarplotOTU)
#reshaping data got ggplot
CFBarplotOTU <- otu_table(CFBarplotOTU,taxa_are_rows = FALSE)
CFBarplot <- psmelt(CFBarplotOTU)
colnames(CFBarplot) <- c("Genus","Sample","Abundance")
CFBarplot <- CFBarplot[order(CFBarplot$Abundance),]



pdf("CFRABarplot.pdf", height = 10, width = 20)
 ggplot(CFBarplot, aes(x = Sample, y = Abundance, fill = Genus, group = Abundance)) + geom_bar(stat = 'identity') + theme(legend.position = "bottom") +theme_bw(base_size =25)+ theme(legend.position = "bottom") + scale_fill_manual(values = Rainbow2) +xlab("Age and Health Status") +ylab("Relative Abundance %")
dev.off()


#CF Barplot by Subject
CFsubjRA <- merge_samples(CFBarplotOTU, CFsamp$unq_id, fun = mean)
CFsubjRA <- transform_sample_counts(CFsubjRA, function(x) x / sum(x))
rowSums(CFsubjRA)
colSums(CFsubjRA)
CFsubjBP<- psmelt(CFsubjRA)
colnames(CFsubjBP) <- c("Genus","Sample","Abundance")
CFsubjBP <- CFsubjBP[order(CFsubjBP$Abundance),]

pdf("CFsubjRABarplot.pdf", height = 10, width = 20)
 ggplot(CFsubjBP, aes(x = Sample, y = Abundance, fill = Genus, group = Abundance)) + geom_bar(stat = 'identity') + theme(legend.position = "bottom") +theme_bw(base_size =25)+ theme(legend.position = "bottom") + scale_fill_manual(values = Rainbow2) +xlab("Age and Health Status") +ylab("Relative Abundance %")
dev.off()

BP12M <- as.data.frame(Top12MRA@otu_table@.Data)[Top12MRA@sam_data$Status == "CF",]
colnames(BP12M) <- Top12MRA@tax_table[,6]
colnames(BP12M)[4]<-paste("o_",Top12MRA@tax_table[4,5], "_g_NA",sep="")
#colnames(BP9M)[16]<-paste("o_",Top9MRA@tax_table[16,5], "_g_NA",sep="")
colnames(BP12M)
rownames(BP12M) <-substr(rownames(BP12M), 1,3)
rownames(BP12M)
BP12M <- otu_table(BP12M, taxa_are_rows = FALSE)
BP12M <- psmelt(BP12M)
colnames(BP12M) <- c("Genus","Sample","Abundance")
BP12M <- BP12M[order(BP9M$Abundance),]

pdf("CF12MRABarplot.pdf", height = 10, width = 20)
 ggplot(BP12M, aes(x = Sample, y = Abundance, fill = Genus, group = Abundance)) + geom_bar(stat = 'identity') + theme(legend.position = "bottom") +theme_bw(base_size =25)+ theme(legend.position = "bottom") + scale_fill_manual(values = Rainbow2) +
   xlab("Age and Health Status") +ylab("Relative Abundance %")
dev.off()

```

```{r RAplot, echo = FALSE}
                                

A20merge <- merge_samples(phylo20RA,sampdf$Status, fun = mean)
rowSums(A20merge@otu_table@.Data)
colSums(A20merge@otu_table@.Data)
A20mergeRA <- transform_sample_counts(A20merge, function(x) x / sum(x))


#Find difference in means
meandif <- A20mergeRA@otu_table@.Data[1,] - A20mergeRA@otu_table@.Data[2,]

Gen20 <- phylo20RA@tax_table[order(meandif),6]
#replace NA with actual taxa
Gen20[9]<-paste("o_",phylo20RA@tax_table[4,5], "_g_NA",sep="")
Gen20

#########################################################################

factor1 <- rownames(sampdf[sampdf$Status == "CF",])
factor2 <- rownames(sampdf[sampdf$Status == "HC",])
#RA plot
 pdf(file = "RAtest2.pdf", width = 18, height = 10)
    par(mar=c(7.1,30.1,7.1,15.1))
    plot(0,1, xlim = c(-1,1), ylim = c(1,20), xlab = "Relative abundance %", ylab = "", yaxt = 'n', xaxt = 'n',cex.lab = 2)
    title(main = "Top taxa differences", cex.main = 2.5)
    grid(ny = 20)
    par(xpd = TRUE)
    legend(1.1,20.75, legend = c ("Sample Relative Abundances", "Mean Relative Abundance","Difference in Means"), col = c("black","steelblue","red"), pch = 16, title = "Legend", cex = 1)
    lines(x = c(0,0),y = c(0.25,20.75))

     for (i in 1:20){
       #plot relative abundances
      j = names(sort(meandif))[i]
      points(x = -phylo20RA@otu_table@.Data[factor = factor1,j],rep(i,length(factor1)), type = 'p', pch = 16, col = "black")
      points(x = phylo20RA@otu_table@.Data[factor = factor2,j],rep(i,length(factor2)), type = 'p', pch = 16, col = "black")
      
     }

    #plot means and difference in means
    points(x = -A20mergeRA@otu_table@.Data[2,order(meandif)], y = c(1:20), xlim = c(-1,1),xlab = "", ylab = "", pch = 16, col = 'steelblue1',
          yaxt = 'n', xaxt = 'n',cex = 1.5)
   points(x = A20mergeRA@otu_table@.Data[1,order(meandif)], y = c(1:20), xlim = c(-1,1),xlab = "", ylab = "", pch = 16, col = 'steelblue1',
         yaxt = 'n', xaxt = 'n',cex = 1.5)
    points(x = sort(meandif), y = c(1:20), xlim = c(-1,1),xlab = "Relative abundance%",ylab = "", pch = 16, col = 'red',
           yaxt = 'n', xaxt = 'n', cex = 1.75)
    #add axis labels
    axis(2, at = c(1:20), labels = Gen20, las = 2,cex.axis =2, font = 3)
    axis(1,at = c(-1,-0.5,0,0.5,1), labels = c("100%","CF","0%","HC","100%"),cex.axis = 2)
    #lines(x = rep(0,27), y = c(0:26))
    
    dev.off()
###################################################################################################
    #######################################################################################
    
    
Genus12M <- tax_glom(phylo12M,taxrank = "Genus", NArm = FALSE)
Top20 <- names(sort(taxa_sums(Genus12M), TRUE)[1:20])
Top12M <- prune_taxa(Top20, Genus12M)
Top12MRA <-  transform_sample_counts(Top12M, function(x) x / sum(x)) 
A20merge12M <- merge_samples(Top12M,sampdf$Status[sampdf$TimePeriod == "12M"], fun = mean)
rowSums(Top12MRA@otu_table@.Data)
colSums(Top12MRA@otu_table@.Data)
mergeRA12M <- transform_sample_counts(A20merge12M, function(x) x / sum(x))
rowSums(mergeRA12M@otu_table@.Data)
colSums(mergeRA12M@otu_table@.Data)

#Find difference in means
meandif12M <- mergeRA12M@otu_table@.Data[1,] - mergeRA12M@otu_table@.Data[2,]

Gen12M <- Top12MRA@tax_table[,6]
#check for NA
Gen12M
#replace NA with actual taxa
Gen12M[4]<-paste("o_",Top12MRA@tax_table[4,5], "_g_NA",sep="")


Gen12M
#ordering Genera labels for plotting
Gen12M <- Gen12M[order(meandif12M)]
#########################################################################

factor1 <- rownames(sampdf[sampdf$Status == "CF"&sampdf$TimePeriod == "12M",])
factor2 <- rownames(sampdf[sampdf$Status == "HC"&sampdf$TimePeriod == "12M",])
#RA plot
 pdf(file = "RA12M.pdf", width = 18, height = 10)
    par(mar=c(7.1,30.1,7.1,15.1))
    plot(0,1, xlim = c(-1,1), ylim = c(1,20), xlab = "Relative abundance %", ylab = "", yaxt = 'n', xaxt = 'n',cex.lab = 2)
    title(main = "Top taxa differences at 12 months", cex.main = 2.5)
    grid(ny = 20)
    par(xpd = TRUE)
    legend(1.1,20.75, legend = c ("Sample Relative Abundances", "Mean Relative Abundance","Difference in Means"), col = c("black","steelblue","red"), pch = 16, title = "Legend", cex = 1)
    lines(x = c(0,0),y = c(0.25,20.75))

     for (i in 1:20){
       #plot relative abundances
      j = names(sort(meandif12M))[i]
      points(x = -Top12MRA@otu_table@.Data[factor = factor1,j],rep(i,length(factor1)), type = 'p', pch = 16, col = "black")
      points(x = Top12MRA@otu_table@.Data[factor = factor2,j],rep(i,length(factor2)), type = 'p', pch = 16, col = "black")
      
     }

    #plot means and difference in means
    points(x = -mergeRA12M@otu_table@.Data[2,order(meandif12M)], y = c(1:20), xlim = c(-1,1),xlab = "", ylab = "", pch = 16, col = 'steelblue1',
          yaxt = 'n', xaxt = 'n',cex = 1.75)
   points(x = mergeRA12M@otu_table@.Data[1,order(meandif12M)], y = c(1:20), xlim = c(-1,1),xlab = "", ylab = "", pch = 16, col = 'steelblue1',
         yaxt = 'n', xaxt = 'n',cex = 1.75)
    points(x = sort(meandif12M), y = c(1:20), xlim = c(-1,1),xlab = "Relative abundance%",ylab = "", pch = 16, col = 'red',
           yaxt = 'n', xaxt = 'n', cex = 1.5)
    #add axis labels
    axis(2, at = c(1:20), labels = Gen12M, las = 2,cex.axis =2, font = 3)
    axis(1,at = c(-1,-0.5,0,0.5,1), labels = c("100%","CF","0%","HC","100%"),cex.axis = 2)
    #lines(x = rep(0,27), y = c(0:26))
    
    dev.off()

#Comparing top 20 genera    
mt12M20 <- mt(Top12M, "Status")
write.csv(mt12M20,file = "CFHC12Mtop20.csv")

```


```{r RAdotplot, echo = FALSE}

#extracting Bacteroides relative abundances
BacteroidesRA <- phylo20RA@otu_table@.Data
colnames(BacteroidesRA) <- phylo20RA@tax_table@.Data[,6] 
BacteroidesRAdat <- cbind(BacteroidesRA[,"Bacteroides"], sampdf)
colnames(BacteroidesRAdat) <- c("Bacteroides", colnames(sampdf))

#relevel StatusAge for plotting
BacteroidesRAdat$StatusAge <- factor(BacteroidesRAdat$StatusAge, levels = c("6W HC","4M HC","6M HC","9M HC","12M HC","6W CF","4M CF","6M CF","9M CF","12M CF"))

pdf("BacteroidesRA.pdf", height = 8, width = 15)
ggplot(BacteroidesRAdat, aes(x = StatusAge, y = Bacteroides, fill = StatusAge))+
  geom_boxplot() +
  scale_fill_manual(values =c(Greens,Blues))+
  scale_y_continuous(labels = c("0","25","50","75","100"))+
  theme_bw(base_size =25)+
   xlab("Age and Health Status") +ylab("Bacteroides Relative Abundance %")
dev.off()

wilcox.test(BacteroidesRAdat$Bacteroides[BacteroidesRAdat$TimePeriod == "6W"]~BacteroidesRAdat$Status[BacteroidesRAdat$TimePeriod == "6W"])
wilcox.test(BacteroidesRAdat$Bacteroides[BacteroidesRAdat$TimePeriod == "4M"]~BacteroidesRAdat$Status[BacteroidesRAdat$TimePeriod == "4M"])
wilcox.test(BacteroidesRAdat$Bacteroides[BacteroidesRAdat$TimePeriod == "6M"]~BacteroidesRAdat$Status[BacteroidesRAdat$TimePeriod == "6M"])
wilcox.test(BacteroidesRAdat$Bacteroides[BacteroidesRAdat$TimePeriod == "9M"]~BacteroidesRAdat$Status[BacteroidesRAdat$TimePeriod == "9M"])
wilcox.test(BacteroidesRAdat$Bacteroides[BacteroidesRAdat$TimePeriod == "12M"]~BacteroidesRAdat$Status[BacteroidesRAdat$TimePeriod == "12M"])
```


```{r BifidoHist, echo = FALSE}

#extracting Bacteroides relative abundances
BifidoRA <- phylo20RA@otu_table@.Data
colnames(BifidoRA) <- phylo20RA@tax_table@.Data[,6] 
BifidoRAdat <- cbind(BifidoRA[,"Bifidobacterium"], sampdf)
colnames(BifidoRAdat) <- c("Bifidobacterium", colnames(sampdf))

#relevel StatusAge for plotting
BifidoRAdat$StatusAge <- factor(BifidoRAdat$StatusAge, levels = c("6W HC","4M HC","6M HC","9M HC","12M HC","6W CF","4M CF","6M CF","9M CF","12M CF"))

pdf("BifidoHistAll.pdf", height = 4, width = 20)
ggplot(BifidoRAdat[BifidoRAdat$Status=="HC",], aes(x =Bifidobacterium, fill = StatusAge))+
  geom_histogram(bins = 8) +
  scale_fill_manual(values =c(Blues))+
  facet_wrap(BifidoRAdat$TimePeriod[BifidoRAdat$Status=="HC"],ncol = 5)
dev.off()

pdf("BifidoRA.pdf", height = 8, width = 15)
ggplot(BifidoRAdat, aes(x = StatusAge, y = Bifidobacterium, fill = StatusAge))+
  geom_boxplot() +
  scale_fill_manual(values =c(Greens,Blues))+
  theme_bw(base_size =25)
dev.off()
```

```{r Escherichia, echo = FALSE}

#extracting Bacteroides relative abundances
EscherichiaRA <- phylo20RA@otu_table@.Data
colnames(EscherichiaRA) <- phylo20RA@tax_table@.Data[,6] 
EscherichiaRAdat <- cbind(EscherichiaRA[,"Escherichia/Shigella"], sampdf)
colnames(EscherichiaRAdat) <- c("EscherichiaShigella", colnames(sampdf))

#relevel StatusAge for plotting
EscherichiaRAdat$StatusAge <- factor(EscherichiaRAdat$StatusAge, levels = c("6W HC","4M HC","6M HC","9M HC","12M HC","6W CF","4M CF","6M CF","9M CF","12M CF"))

pdf("EscherichiaRA.pdf", height = 8, width = 15)
ggplot(EscherichiaRAdat, aes(x = StatusAge, y = EscherichiaShigella, fill = StatusAge))+
  geom_boxplot() +
  scale_fill_manual(values =c(Greens,Blues))+
  theme_bw(base_size =25)
dev.off()


```

```{r BifBact, echo = FALSE}


pdf("BifBactHC.pdf", height = 8, width = 11)
ggplot(data = BacteroidesRAdat[BacteroidesRAdat$Status == "HC",], aes(x = BacteroidesRAdat$Bacteroides[BacteroidesRAdat$Status == "HC"], y = BifidoRAdat$Bifidobacterium[BacteroidesRAdat$Status == "HC"], color= TimePeriod))+
  geom_point(size = 3) +
  scale_color_manual(values =c(Greens), name = "Time Period", labels = c("6 Weeks", "4 Months", "6 Months", "9 Months", "12 Months"))+
  scale_y_continuous(labels = c("0","25","50","75","100"), limits = c(0,1))+
  scale_x_continuous(labels = c("0","25","50","75","100"), limits = c(0,1))+
  theme_bw(base_size =25)+
  ylab("Bifidobacterium Relative Abundance %") +xlab("Bacteroides Relative Abundance %")+
  geom_abline(slope = -1, intercept = 1)
dev.off()

pdf("BifBactCF.pdf", height = 8, width = 11)
ggplot(data = BacteroidesRAdat[BacteroidesRAdat$Status == "CF",], aes(x = BacteroidesRAdat$Bacteroides[BacteroidesRAdat$Status == "CF"], y = BifidoRAdat$Bifidobacterium[BacteroidesRAdat$Status == "CF"], color= TimePeriod))+
  geom_point(size = 3) +
  scale_color_manual(values =c(Blues), name = "Time Period", labels = c("6 Weeks", "4 Months", "6 Months", "9 Months", "12 Months"))+
  scale_y_continuous(labels = c("0","25","50","75","100"), limits = c(0,1))+
  scale_x_continuous(labels = c("0","25","50","75","100"), limits = c(0,1))+
  theme_bw(base_size =25)+
  ylab("Bifidobacterium Relative Abundance %") +xlab("Bacteroides Relative Abundance %")+
  geom_abline(slope = -1, intercept = 1)
dev.off()

pdf("BifBact.pdf", height = 8, width = 18)
ggplot(data = BacteroidesRAdat, aes(x = BacteroidesRAdat$Bacteroides, y = BifidoRAdat$Bifidobacterium, color= StatusAge))+
  geom_point(size = 3) +
  scale_color_manual(values =c(Blues,Greens), name = "Status Age", labels = c("CF 6 Weeks", "CF 4 Months", "CF 6 Months", "CF 9 Months", "CF 12 Months","HC 6 Weeks", "HC 4 Months", "HC 6 Months", "HC 9 Months", "HC 12 Months"))+
  scale_y_continuous(labels = c("0%","25%","50%","75%","100%"), limits = c(0,1))+
  scale_x_continuous(labels = c("0%","25%","50%","75%","100%"), limits = c(0,1))+
  theme_bw(base_size =25)+
  ylab("Bifidobacterium Relative Abundance %") +xlab("Bacteroides Relative Abundance %")+
  geom_segment(x = 0, y = 1, xend = 1, yend = 0 , lineend = "round", color = "black")+
  facet_wrap(facets = BacteroidesRAdat$Status, ncol = 2, labeller = as_labeller(c("HC" = "Control","CF" = "CF")))
dev.off()


```


```{r tab1, echo = FALSE}
# % of babies fed by each method (breast, formula, or mixed)
BF <- vector()
Mixed <- vector()
FF <- vector()
for (i in levels(sampdf$StatusAge)){
  tempBF <- length(sampdf$dFeedingModeED[sampdf$StatusAge == i & sampdf$dFeedingModeED == 1])/length(sampdf$dFeedingModeED[sampdf$StatusAge == i])
  BF <- c(BF, tempBF)
  tempMix <-length(sampdf$dFeedingModeED[sampdf$StatusAge == i & sampdf$dFeedingModeED == 3])/length(sampdf$dFeedingModeED[sampdf$StatusAge == i])
  Mixed<- c(Mixed, tempMix)
  tempFF <-length(sampdf$dFeedingModeED[sampdf$StatusAge == i & sampdf$dFeedingModeED == 2])/length(sampdf$dFeedingModeED[sampdf$StatusAge == i])
  FF <- c(FF, tempFF)
}



feedingPerc <- cbind(BF, FF, Mixed)
rownames(feedingPerc) <- levels(sampdf$StatusAge)
colnames(feedingPerc)<- c("Breast", "Formula", "Mixed")

#percent delivered vaginally
DelPerc <- vector()
for (j in levels(CFsamp$TimePeriod)){
  temp <- length(CFsamp$DeliveryMode[CFsamp$TimePeriod == j & CFsamp$DeliveryMode== "V"])/length(CFsamp$DeliveryMode[CFsamp$TimePeriod == j])
  DelPerc <- c(DelPerc,temp)
}

# % pancreatic insufficient
pancPerc <- vector()
for (j in levels(CFsamp$TimePeriod)){
  temp <- length(CFsamp$PancIns[CFsamp$TimePeriod == j & CFsamp$PancIns== "Yes"])/length(CFsamp$PancIns[CFsamp$TimePeriod == j])
  pancPerc <- c(pancPerc,temp)
}

```